server:
  port: 8080

spring:
  application:
    name: iam-service

  datasource:
    # 'postgres-db' là tên service chúng ta đặt trong docker-compose.yml
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/iam_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: false
    show-sql: true

application:
  security:
    jwt:
      secret-key: CceAYTEK9XB5w/ibsdi5pvuNynAwNfDvGI7y+BD3ziA=
      expiration: 86400000 # 1 ngày
      refresh-token:
        expiration: 604800000       # Refresh Token: 7 ngày

eureka:
  client:
    enabled: false
